# Model parameters.
model:
  model: "siamunet_conc_3d"
  2d_loss: 'bce' 
  3d_loss: 'mse'
  num_classes: 3
  loss_weights: [1,1]
  2d_loss_weights: [0.05, 0.95, 0.95]
  pretrain_path: 'results/CD_siamunet_conc_levir/version_3/checkpoints/epoch=299-step=33600.ckpt'
  

# Optimization parameters.
optim:
  num_epochs: 300
  lr: 0.0001
  optim_type: "adamw" 
  momentum: 0.9
  nesterov: False
  beta: [0.9, 0.999]
  end_lr: 0.000005
  weight_decay: 0.001
  lr_schedule_type: "step_lr"
  step: 300 
  gamma: 0.75
  last_epoch: 10

# Data parameters:
data:
  max_value: 83.266
  min_value: -27.291
  augmentations: True
  mean: [0.5896145210542503, 0.6210658017517566, 0.591661801751776]
  std: [0.1898555514094201, 0.19114699478664082, 0.21242997453209553]
  batch_size: 2
  train:
    path: ['../data/amsterdam_025/train','../data/rotterdam_025/train','../data/utrecht_025/train']
  val:
    path: ['../data/amsterdam_025/val','../data/rotterdam_025/val','../data/utrecht_025/val']
  test:
    path: ['../data/amsterdam_025/test','../data/rotterdam_025/test','../data/utrecht_025/test']
    
  sets: ['img_1k/','dsm_1k/','mask2d_1k/','mask3d_1k/']
